import type { Metadata } from "next";
import "./globals.css";
import { AppContainer, Footer, Header } from "./component";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Header />
				<AppContainer>{children}</AppContainer>
				<Footer />
			</body>
		</html>
	);
}
